name = "GoGeek"
license = "MIT"
licenselink = "https://github.com/ssiyad/gogeektheme/blob/master/LICENSE.md"
description = "A minimal theme for Hugo"
tags = ["clean", "fast", "responsive", "typography", "disqus", "light", "dark", "syntax-highlighting"]
features = ["clean", "fast", "responsive", "typography", "disqus", "light", "dark", "syntax-highlighting"]
min_version = "0.40.0"

[author]
    name = "Sabu Siyad"
    homepage = "https://ssiyad.me/"
    repo = "https://github.com/ssiyad/gogeektheme"

[original]
    name = "Gökmen Görgen"
    homepage = "https://gokmengorgen.net"
    repo = "https://github.com/gkmngrgn/hugo-alageek-theme"

